#Coffee-Beans light
general {

    border_size = 3

    col.active_border = rgb(854719)
    col.inactive_border = rgb(b98f4e)

}

decoration {
    rounding = 10
    rounding_power = 10

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgb(e0d9d5)
    }

    blur {
        enabled = true
        size = 5
        passes = 1

        vibrancy = 0.1696
    }
}
exec =sleep 1 && ~/Rice/Themes/Coffee-Beans/Wallpaper/Light.sh
